version: '3.6'

services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: hive
      POSTGRES_DB: hive
    ports:
      - 5433:5432

  redis:
    image: redis:alpine

  migration:
    build:
      context: .
      dockerfile: devops/Dockerfile
    depends_on:
      - database
    environment:
      DATABASE_URI: postgres://hive:123@database:5432/hive
    command: "hive migrate"

  hive:
    build:
      context: .
      dockerfile: devops/Dockerfile
    depends_on:
      - migration
      - redis
    environment:
      DATABASE_URI: postgres://hive:123@database:5432/hive
      REDIS_URL: redis:6379
    command: "hive"
    ports:
      - 8080:8080