on:
  push:
    tags:
      - 0.*
      - 1.*

env:
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE: docker.pkg.github.com/${{ github.repository }}:${{ github.ref }}
  ACTOR: ${{ github.actor }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: docker

    steps:
      - uses: actions/checkout@v1
      - name: set image variable
        run: echo ::set-env name=IMAGE::$(echo $IMAGE | sed -e "s/refs\/tags\///g")
      - name: test image var
        run: echo $IMAGE
      - name: build image
        run: docker build -t $IMAGE -f ./devops/Dockerfile .
      - name: registry login
        run: docker login --username $ACTOR --password $REGISTRY_TOKEN docker.pkg.github.com
      - name: push image to registry
        run: docker push $IMAGE